// Lộ trình ngữ pháp cố định (dữ liệu tĩnh, không cần gọi AI) — dùng để tạo buổi luyện nói nhắm đúng 1 điểm ngữ pháp.
// LƯU Ý: tiến độ được lưu theo vị trí (index) của mục trong cấp độ — khi bổ sung nội dung mới,
// hãy THÊM VÀO CUỐI mỗi cấp độ thay vì chèn vào giữa để không làm lệch tiến độ đã đánh dấu.

function t(name, pattern, explanationVi, example) {
  return { name, pattern, explanationVi, example };
}

const EN_LEVELS = [
  {
    id: 'a1',
    label: 'A1 · Mới bắt đầu',
    topics: [
      t('Động từ "to be"', 'I am / You are / He is...', 'Chia động từ "to be" theo chủ ngữ, nền tảng của mọi câu giới thiệu.', 'I am a student.'),
      t('Thì hiện tại đơn', 'S + V(s/es)', 'Diễn tả thói quen, sự thật hiển nhiên.', 'She works in Hanoi.'),
      t('There is / There are', 'There is + danh từ số ít; There are + danh từ số nhiều', 'Diễn tả sự tồn tại của vật/người.', 'There is a book on the table.'),
      t('Tính từ sở hữu', 'my / your / his / her / our / their', 'Chỉ sự sở hữu, đứng trước danh từ.', 'This is my phone.'),
      t('Động từ khuyết thiếu "can"', 'S + can + V(nguyên mẫu)', 'Diễn tả khả năng hoặc xin phép.', 'I can swim.'),
      t('Câu hỏi Wh-', 'What/Where/When/Who + do/does + S + V?', 'Cấu trúc câu hỏi thông tin cơ bản.', 'Where do you live?'),
      t('Mạo từ a / an / the', 'a/an + danh từ nhắc lần đầu; the + danh từ đã xác định', 'Chọn đúng mạo từ theo việc người nghe đã biết đến vật đó hay chưa.', 'I bought a book. The book is very interesting.'),
      t('Danh từ số nhiều', 'N + s/es; bất quy tắc: man→men, child→children', 'Cách chuyển danh từ sang số nhiều, gồm cả các từ bất quy tắc hay gặp.', 'There are two children in the park.'),
      t('This / That / These / Those', 'this-these (gần); that-those (xa)', 'Từ chỉ định theo khoảng cách và số lượng.', 'These shoes are mine, and those bags are hers.'),
      t('Giới từ chỉ nơi chốn', 'in / on / under / next to / between / behind', 'Mô tả vị trí của người và vật.', 'The cat is under the table, next to the chair.'),
      t('Giới từ thời gian in / on / at', 'at + giờ; on + thứ, ngày; in + tháng, năm, buổi', 'Bộ ba giới từ thời gian dễ nhầm nhất ở trình độ đầu.', 'I have a meeting at 9 a.m. on Monday.'),
      t('Trạng từ tần suất', 'always / usually / often / sometimes / never (trước V thường, sau "to be")', 'Nói về mức độ thường xuyên của thói quen.', 'I usually get up at six, but I never eat breakfast.'),
      t('Câu mệnh lệnh & Let\'s', 'V(nguyên mẫu)...!; Don\'t + V...; Let\'s + V', 'Ra chỉ dẫn, yêu cầu và rủ rê làm gì đó cùng nhau.', 'Open your book. Don\'t be late. Let\'s go!'),
      t('like / love / hate + V-ing', 'S + like/love/hate + V-ing', 'Nói về sở thích với danh động từ.', 'I love cooking, but I hate washing dishes.'),
    ],
  },
  {
    id: 'a2',
    label: 'A2 · Sơ cấp',
    topics: [
      t('Thì quá khứ đơn', 'S + V-ed / V2', 'Diễn tả hành động đã xảy ra và kết thúc trong quá khứ.', 'I visited Japan last year.'),
      t('Thì hiện tại tiếp diễn', 'S + am/is/are + V-ing', 'Diễn tả hành động đang xảy ra ngay lúc nói.', 'I am studying English now.'),
      t('So sánh hơn & so sánh nhất', 'adj-er/more + adj than...; the + adj-est', 'So sánh giữa 2 hay nhiều sự vật.', 'This book is more interesting than that one.'),
      t('Tương lai gần "be going to"', 'S + am/is/are + going to + V', 'Diễn tả dự định, kế hoạch đã quyết định.', 'We are going to travel next month.'),
      t('Have to / Must', 'S + have to/must + V', 'Diễn tả nghĩa vụ, sự bắt buộc.', 'I have to finish this report today.'),
      t('Some / Any', 'some (câu khẳng định), any (phủ định/nghi vấn)', 'Dùng với danh từ đếm được số nhiều và không đếm được.', 'Is there any milk left?'),
      t('Much / Many / A lot of', 'many + đếm được; much + không đếm được; a lot of + cả hai', 'Nói về số lượng với danh từ đếm được và không đếm được.', 'I don\'t have much time, but I have a lot of ideas.'),
      t('Thì quá khứ tiếp diễn', 'S + was/were + V-ing', 'Diễn tả hành động đang diễn ra tại một thời điểm trong quá khứ, thường làm nền cho hành động khác.', 'I was cooking when you called me.'),
      t('Would like', 'S + would like + N / to V', 'Mời mọc và yêu cầu một cách lịch sự, mềm hơn "want".', 'I\'d like a coffee, please. Would you like to join us?'),
      t('Should / Shouldn\'t', 'S + should/shouldn\'t + V', 'Đưa ra lời khuyên.', 'You should see a doctor. You shouldn\'t work so late.'),
      t('Too / Not enough', 'too + adj; not + adj + enough', 'Diễn tả mức độ quá nhiều hoặc chưa đủ.', 'This coffee is too hot, and my desk isn\'t big enough.'),
      t('Liên từ because / so / but', 'mệnh đề + because/so/but + mệnh đề', 'Nối câu để giải thích lý do, kết quả và sự tương phản.', 'I stayed home because it was raining, so I watched a movie.'),
      t('Đại từ sở hữu', 'mine / yours / his / hers / ours / theirs', 'Thay cho "tính từ sở hữu + danh từ" để tránh lặp.', 'This umbrella isn\'t mine — maybe it\'s yours.'),
      t('Verb + to V / V-ing nhập môn', 'want/decide/hope + to V; enjoy/finish + V-ing', 'Nhóm động từ phổ biến đi kèm to V hoặc V-ing.', 'I want to travel, and I enjoy meeting new people.'),
    ],
  },
  {
    id: 'b1',
    label: 'B1 · Trung cấp',
    topics: [
      t('Thì hiện tại hoàn thành', 'S + have/has + V3', 'Diễn tả hành động bắt đầu trong quá khứ, còn liên quan hiện tại hoặc chưa xác định thời điểm.', 'I have lived here for five years.'),
      t('Câu điều kiện loại 1', 'If + S + V(hiện tại), S + will + V', 'Diễn tả điều kiện có thật ở hiện tại/tương lai.', 'If it rains, I will stay home.'),
      t('Will vs Going to', 'will: quyết định tức thời; going to: kế hoạch đã định', 'Phân biệt 2 cách nói về tương lai.', 'I think I will call her later.'),
      t('Modal suy đoán: must/might/can\'t', 'S + must/might/can\'t + V', 'Diễn tả mức độ chắc chắn khi suy đoán.', 'He must be tired after the trip.'),
      t('Used to', 'S + used to + V(nguyên mẫu)', 'Diễn tả thói quen/trạng thái trong quá khứ nay không còn.', 'I used to live in Da Nang.'),
      t('Mệnh đề quan hệ (who/which/that)', 'Noun + who/which/that + mệnh đề', 'Bổ nghĩa cho danh từ đứng trước.', 'The man who called you is my colleague.'),
      t('Hiện tại hoàn thành vs Quá khứ đơn', 'have V3 (chưa rõ/còn liên quan) vs V2 (thời điểm xác định)', 'Cặp thì gây nhầm lẫn nhiều nhất ở trình độ trung cấp.', 'I have seen that movie. I saw it last Friday.'),
      t('Thì quá khứ hoàn thành', 'S + had + V3', 'Diễn tả hành động xảy ra trước một hành động khác trong quá khứ.', 'When I arrived, the meeting had already started.'),
      t('Câu bị động nhập môn', 'S + am/is/are/was/were + V3', 'Bị động ở thì hiện tại đơn và quá khứ đơn.', 'This bridge was built in 1990.'),
      t('Câu tường thuật nhập môn', 'S + said (that) / told + O + (that) + mệnh đề lùi thì', 'Thuật lại lời nói với say/tell và quy tắc lùi thì cơ bản.', 'She said that she was busy.'),
      t('Câu hỏi đuôi', 'mệnh đề khẳng định, + trợ động từ phủ định + S?', 'Xác nhận thông tin hoặc kéo người nghe vào hội thoại.', 'You\'re from Hanoi, aren\'t you?'),
      t('Cụm động từ thông dụng', 'phrasal verbs: get up, look for, turn on, give up...', 'Các cụm động từ xuất hiện dày đặc trong hội thoại hàng ngày.', 'I\'m looking for my keys — don\'t give up on me!'),
      t('so / such ... that', 'so + adj + that...; such + (a/an) + adj + N + that...', 'Nhấn mạnh mức độ dẫn đến một kết quả.', 'It was such a good film that I watched it twice.'),
      t('stop / remember / try + V-ing vs to V', 'stop to V (dừng để làm) vs stop V-ing (bỏ hẳn)', 'Nhóm động từ đổi nghĩa tuỳ theo đi với to V hay V-ing.', 'I stopped drinking coffee. / I stopped to drink coffee.'),
    ],
  },
  {
    id: 'b2',
    label: 'B2 · Trung cao cấp',
    topics: [
      t('Câu điều kiện loại 2', 'If + S + V-ed, S + would + V', 'Diễn tả tình huống giả định không có thật ở hiện tại.', 'If I had more time, I would learn Japanese.'),
      t('Thì hiện tại hoàn thành tiếp diễn', 'S + have/has been + V-ing', 'Nhấn mạnh quá trình liên tục từ quá khứ đến hiện tại.', 'I have been working here since 2020.'),
      t('Câu bị động', 'S + be + V3 (+ by O)', 'Nhấn mạnh vào đối tượng chịu tác động thay vì người thực hiện.', 'This report was written by my manager.'),
      t('Câu tường thuật', 'S + said/told + (that) + mệnh đề lùi thì', 'Thuật lại lời nói của người khác.', 'She said that she was tired.'),
      t('Suy đoán quá khứ: must have / might have', 'S + must/might/can\'t + have + V3', 'Suy đoán về một sự việc đã xảy ra.', 'He must have forgotten the meeting.'),
      t('Gerund vs Infinitive', 'V-ing (danh động từ) vs to + V (động từ nguyên mẫu)', 'Một số động từ theo sau bởi V-ing, số khác theo sau bởi to-V.', 'I enjoy reading, but I decided to leave early.'),
      t('Câu điều kiện loại 3', 'If + S + had + V3, S + would have + V3', 'Giả định trái với quá khứ — điều đã không xảy ra.', 'If I had known, I would have called you.'),
      t('Wish / If only', 'wish + V-ed (hiện tại); wish + had V3 (quá khứ)', 'Diễn tả mong ước trái với thực tế hoặc nuối tiếc.', 'I wish I spoke Japanese. If only I had studied harder.'),
      t('Thể sai khiến have/get something done', 'S + have/get + O + V3', 'Nói về việc nhờ/thuê người khác làm cho mình.', 'I had my laptop repaired yesterday.'),
      t('Mệnh đề quan hệ không xác định', 'Noun, + who/which + mệnh đề, ...', 'Bổ sung thông tin phụ (có dấu phẩy), không dùng "that".', 'My boss, who lives in Tokyo, calls me every week.'),
      t('Tương lai tiếp diễn & hoàn thành', 'will be + V-ing; will have + V3', 'Nói về hành động đang diễn ra hoặc đã hoàn tất tại một mốc tương lai.', 'By next year, I will have finished this project.'),
      t('Từ nối trang trọng', 'however / therefore / despite / in spite of / although', 'Liên kết ý tương phản và nhân quả trong văn nói/viết trang trọng.', 'Despite the rain, the event went ahead. However, few people came.'),
      t('Lượng từ nâng cao', 'plenty of / a great deal of / hardly any / a number of', 'Diễn đạt số lượng tinh tế hơn much/many.', 'We have plenty of time, but hardly any budget.'),
      t('Mạo từ nâng cao', 'the + nhóm chung (the rich); không mạo từ với khái niệm chung', 'Các quy tắc mạo từ khó: khái niệm trừu tượng, nhóm người, tên riêng.', 'Life is short. The unemployed need more support.'),
    ],
  },
  {
    id: 'c1',
    label: 'C1 · Cao cấp',
    topics: [
      t('Câu điều kiện hỗn hợp', 'If + S + had + V3, S + would + V(nguyên mẫu)', 'Kết hợp điều kiện ở quá khứ với kết quả ở hiện tại.', 'If I had studied harder, I would have a better job now.'),
      t('Đảo ngữ nhấn mạnh', 'Never/Rarely/Not only + trợ động từ + S + V', 'Đảo trật tự câu để nhấn mạnh, thường dùng trong văn viết/nói trang trọng.', 'Never have I seen such a beautiful sunset.'),
      t('Câu chẻ (Cleft sentence)', 'It is/was + thành phần nhấn mạnh + that + mệnh đề', 'Nhấn mạnh một thành phần cụ thể trong câu.', 'It was the manager who made the final decision.'),
      t('Thức giả định (Subjunctive)', 'It is essential/important that + S + V(nguyên mẫu)', 'Diễn tả yêu cầu, đề nghị mang tính trang trọng.', 'It is essential that he arrive on time.'),
      t('Mệnh đề phân từ', 'V-ing/V-ed + ..., S + V', 'Rút gọn mệnh đề để câu văn súc tích, trang trọng hơn.', 'Having finished the report, she went home early.'),
      t('Bị động nâng cao: be said to', 'S + is said/believed/reported + to V', 'Truyền đạt thông tin chưa kiểm chứng một cách khách quan, trang trọng.', 'The company is said to be planning a merger.'),
      t('Nhấn mạnh với do/does/did', 'S + do/does/did + V(nguyên mẫu)', 'Thêm trợ động từ vào câu khẳng định để nhấn mạnh sự thật.', 'I did tell you about the meeting!'),
      t('whatever / whoever / however', 'wh-ever + mệnh đề', 'Diễn tả "bất kể/bất cứ" một cách tự nhiên.', 'Whatever you decide, I\'ll support you.'),
      t('Mệnh đề quan hệ rút gọn', 'Noun + V-ing/V3 (lược bỏ who/which + be)', 'Rút gọn mệnh đề quan hệ để câu gọn và chuyên nghiệp hơn.', 'The man standing over there is our new director.'),
      t('Danh hoá (Nominalization)', 'động từ/tính từ → danh từ: decide → decision', 'Biến hành động thành danh từ — dấu hiệu của văn phong học thuật, trang trọng.', 'The implementation of the plan requires approval.'),
      t('Tương lai trong quá khứ', 'was/were going to + V; was/were about to + V', 'Nói về dự định trong quá khứ (thường đã không xảy ra).', 'I was about to leave when the phone rang.'),
      t('needn\'t have vs didn\'t need to', 'needn\'t have + V3 (đã làm, hoá ra thừa) vs didn\'t need to (không cần nên không làm)', 'Cặp modal quá khứ tinh tế thể hiện trình độ cao.', 'You needn\'t have brought a gift — but thank you!'),
    ],
  },
  {
    id: 'c2',
    label: 'C2 · Thành thạo',
    topics: [
      t('Rào đón khi khẳng định (Hedging)', 'It could be argued that... / It would seem that...', 'Giảm nhẹ mức độ chắc chắn của phát biểu, thường dùng trong tranh luận học thuật.', 'It could be argued that the policy has failed.'),
      t('Đảo ngữ nâng cao', 'Rarely/Under no circumstances/Not until + đảo ngữ', 'Các dạng đảo ngữ ít phổ biến hơn, thể hiện trình độ cao.', 'Rarely have I encountered such dedication.'),
      t('Liên từ diễn ngôn học thuật', 'Nevertheless, Furthermore, Consequently...', 'Liên kết ý mạch lạc trong văn nói/viết trang trọng.', 'Nevertheless, the data suggests otherwise.'),
      t('Tỉnh lược & phép thế', 'so/neither + trợ động từ + S', 'Tránh lặp từ bằng cách tỉnh lược hoặc thay thế.', 'She can speak French, and so can I.'),
      t('Cụm động từ thành ngữ nâng cao', 'phrasal verbs: fall through, iron out, hold off...', 'Cụm động từ mang nghĩa bóng, thường gặp trong hội thoại tự nhiên trình độ cao.', 'The negotiations fell through at the last minute.'),
      t('Fronting — đảo thành phần lên đầu', 'Tân ngữ/bổ ngữ + S + V', 'Đưa thành phần lên đầu câu để nhấn mạnh hoặc tạo mạch văn.', 'That kind of behavior I simply cannot accept.'),
      t('Chủ ngữ giả "it" nâng cao', 'It comes as no surprise that... / It goes without saying that...', 'Các mẫu câu mở đầu bằng "it" mang tính thành ngữ, trang trọng.', 'It goes without saying that quality matters most.'),
      t('would rather / may as well', 'would rather + V (thà...); may/might as well + V (đằng nào cũng...)', 'Diễn tả lựa chọn ưu tiên và sự chấp nhận thực tế một cách tự nhiên.', 'I\'d rather stay home. We may as well start without him.'),
      t('Collocations trình độ cao', 'draw a conclusion / pose a threat / bear resemblance', 'Các cụm từ cố định khiến câu nói nghe "bản xứ" hơn hẳn.', 'The findings bear little resemblance to our predictions.'),
      t('Thành ngữ trong hội thoại', 'a double-edged sword / the tip of the iceberg...', 'Dùng thành ngữ đúng ngữ cảnh — dấu hiệu của người nói thành thạo.', 'Remote work is a double-edged sword.'),
      t('Modal quá khứ tinh tế', 'was to have + V3; should have been + V-ing', 'Các tổ hợp modal phức tạp diễn tả kế hoạch đổ vỡ, trách nhiệm bị bỏ lỡ.', 'The ceremony was to have taken place on Sunday.'),
    ],
  },
];

const JA_GENERAL_LEVELS = [
  {
    id: 'n5',
    label: 'N5 · Nhập môn',
    topics: [
      t('Thể lịch sự です・ます', 'Noun/Adj + です; V-ます', 'Thể lịch sự cơ bản dùng trong hầu hết giao tiếp hàng ngày.', '私は学生です。'),
      t('Trợ từ は và が', 'Noun + は (chủ đề); Noun + が (chủ ngữ nhấn mạnh/mới)', 'Phân biệt cách nêu chủ đề và chủ ngữ trong câu.', '猫がいます。'),
      t('Trợ từ を', 'Noun + を + động từ', 'Đánh dấu tân ngữ trực tiếp của động từ.', 'パンを食べます。'),
      t('Trợ từ に và で', 'に (thời gian/điểm đến); で (địa điểm hành động, phương tiện)', 'Hai trợ từ dễ nhầm lẫn nhất ở trình độ đầu.', '図書館で勉強します。'),
      t('Thể て', 'V-て', 'Dùng để nối các hành động liên tiếp hoặc yêu cầu.', '朝ご飯を食べて、学校に行きます。'),
      t('〜ています', 'V-て + います', 'Diễn tả hành động đang diễn ra hoặc thói quen/trạng thái.', '今、雨が降っています。'),
      t('〜たいです', 'V-ます (bỏ ます) + たいです', 'Diễn tả mong muốn của bản thân.', '日本へ行きたいです。'),
      t('Thì quá khứ ました・でした', 'V-ました; Noun/na-Adj + でした; i-Adj + かったです', 'Chia quá khứ cho động từ, danh từ và tính từ.', '昨日、映画を見ました。とても面白かったです。'),
      t('Thể ない', 'V-ない (phủ định thể thường)', 'Phủ định của động từ, nền tảng cho nhiều mẫu ngữ pháp sau này.', '肉を食べない人もいます。'),
      t('Tính từ い・な và cách chia', 'i-Adj: 高い→高くない; na-Adj: 静か→静かじゃない', 'Hai loại tính từ với quy tắc chia hoàn toàn khác nhau.', 'この店は安くて、静かです。'),
      t('Trợ từ の (sở hữu)', 'Noun1 + の + Noun2', 'Nối hai danh từ để chỉ sở hữu hoặc thuộc tính.', 'これは私の友達の車です。'),
      t('Trợ từ へ、と、や', 'へ (hướng đi); と (và - liệt kê hết); や (và - liệt kê ví dụ)', 'Các trợ từ chỉ hướng di chuyển và cách liệt kê danh từ.', '週末は海や山へ行きます。'),
      t('〜ましょう・〜ませんか', 'V-ましょう (rủ); V-ませんか (mời lịch sự)', 'Rủ rê và đề nghị làm gì đó cùng nhau.', '一緒に昼ご飯を食べませんか。'),
      t('Số đếm & trợ số từ', '〜つ、〜人、〜本、〜枚、〜匹...', 'Đếm đồ vật, người, vật dài, vật phẳng... với trợ số từ tương ứng.', 'りんごを三つと、ビールを二本ください。'),
      t('もう・まだ', 'もう + V-ました (đã... rồi); まだ + V-ていません (vẫn chưa...)', 'Diễn tả việc đã hoàn thành hoặc chưa xảy ra.', '昼ご飯はもう食べましたか。いいえ、まだ食べていません。'),
    ],
  },
  {
    id: 'n4',
    label: 'N4 · Sơ cấp',
    topics: [
      t('Thể khả năng（可能形）', 'V-られる/えます', 'Diễn tả khả năng làm được việc gì.', '漢字が読めます。'),
      t('〜てもいいです・〜てはいけません', 'V-て + もいいです / はいけません', 'Xin phép và cấm đoán.', '写真を撮ってもいいですか。'),
      t('〜なければなりません', 'V-ない (bỏ い thêm ければなりません)', 'Diễn tả sự bắt buộc phải làm.', '宿題をしなければなりません。'),
      t('Thể điều kiện ば・たら', 'V/Adj-ば; V-たら', 'Diễn tả điều kiện giả định.', '安ければ、買います。'),
      t('あげる・もらう・くれる', 'あげる (cho), もらう (nhận), くれる (được cho)', 'Diễn tả hướng cho/nhận giữa người nói và người khác.', '友達に本をもらいました。'),
      t('Thể bị động（受身形）', 'V-られる', 'Diễn tả hành động chịu tác động từ người/vật khác.', '先生に褒められました。'),
      t('〜そうです（vẻ ngoài）', 'V-ます/Adj + そうです', 'Nhận xét dựa trên vẻ bề ngoài quan sát được.', 'このケーキはおいしそうです。'),
      t('〜たことがあります', 'V-た + ことがあります', 'Nói về kinh nghiệm đã từng trải qua.', '富士山に登ったことがあります。'),
      t('Thể thường + と思います', '普通形 + と思います / と言いました', 'Nêu ý kiến và thuật lại lời nói bằng thể thường.', '明日は雨が降ると思います。'),
      t('〜てしまいます', 'V-て + しまいます', 'Diễn tả hành động hoàn tất hẳn hoặc điều đáng tiếc lỡ xảy ra.', '財布を忘れてしまいました。'),
      t('〜ておきます', 'V-て + おきます', 'Làm sẵn việc gì đó để chuẩn bị trước.', '会議の前に資料を読んでおきます。'),
      t('〜ながら', 'V-ます (bỏ ます) + ながら', 'Hai hành động diễn ra song song.', '音楽を聞きながら勉強します。'),
      t('〜かもしれません', '普通形 + かもしれません', 'Diễn tả khả năng "có thể, biết đâu" với độ chắc chắn thấp.', '午後は雨が降るかもしれません。'),
      t('〜たり〜たりします', 'V-たり + V-たり + します', 'Liệt kê một vài hành động tiêu biểu trong số nhiều hành động.', '休みの日は映画を見たり、買い物したりします。'),
      t('〜ようになります', 'V(từ điển/ない) + ようになります', 'Diễn tả sự thay đổi: từ không làm được/không làm thành làm được/làm.', '日本語が話せるようになりました。'),
      t('〜でしょう', '普通形 + でしょう', 'Suy đoán "chắc là, có lẽ" — mềm hơn khẳng định trực tiếp.', '明日は晴れるでしょう。'),
    ],
  },
  {
    id: 'n3',
    label: 'N3 · Trung cấp',
    topics: [
      t('Thể sai khiến（使役形）', 'V-させる', 'Diễn tả việc bắt/cho phép ai đó làm gì.', '母は私に部屋を掃除させました。'),
      t('〜わけ', 'V/Adj + わけだ', 'Giải thích lý do, kết luận hợp lý.', '道理で寒いわけだ、雪が降っている。'),
      t('〜はず', 'V/Adj + はずです', 'Diễn tả sự chắc chắn dựa trên suy luận logic.', '彼はもう着いたはずです。'),
      t('〜べき', 'V(từ điển) + べきだ', 'Diễn tả điều nên làm về mặt đạo lý/trách nhiệm.', 'もっと勉強するべきです。'),
      t('Kính ngữ nhập môn（尊敬語・謙譲語）', 'いらっしゃる／まいる', 'Bước đầu làm quen với kính ngữ trong giao tiếp lịch sự.', '先生がいらっしゃいました。'),
      t('〜ことにする・〜ことになっている', 'V(từ điển/ない) + ことにする/ことになっている', 'Diễn tả quyết định cá nhân hoặc quy định đã có.', '毎朝走ることにしています。'),
      t('〜ように', 'V(từ điển/ない) + ように', 'Diễn tả mục đích một cách nhẹ nhàng, thường đi với động từ ý chí.', '忘れないようにメモします。'),
      t('〜そうだ（nghe nói）vs 〜らしい', '普通形 + そうだ (nghe nói); らしい (hình như, nghe đồn)', 'Truyền đạt thông tin nghe được với sắc thái khác nhau.', '天気予報によると、明日は雪だそうです。'),
      t('〜のに', '普通形 + のに', 'Diễn tả sự tương phản kèm cảm giác bất ngờ, tiếc nuối.', 'たくさん勉強したのに、試験に落ちました。'),
      t('〜ば〜ほど', 'V-ば + V(từ điển) + ほど', 'Diễn tả "càng... càng...".', '日本語は勉強すればするほど面白くなります。'),
      t('〜たばかり', 'V-た + ばかり', 'Hành động vừa mới xảy ra (theo cảm nhận của người nói).', '日本に来たばかりで、まだ慣れていません。'),
      t('〜ところ', 'V(từ điển)ところ / V-ているところ / V-たところ', 'Diễn tả thời điểm: sắp làm / đang làm / vừa làm xong.', '今、出かけるところです。'),
      t('〜うちに・〜あいだに', 'V/Adj + うちに (tranh thủ khi còn); あいだに (trong khoảng)', 'Làm gì đó trong khi một trạng thái còn kéo dài.', '熱いうちに食べてください。'),
      t('〜ずに・〜ないで', 'V-ない (bỏ ない) + ずに / V-ないで', 'Làm việc B mà không làm việc A.', '朝ご飯を食べずに出かけました。'),
      t('〜かどうか', '普通形 + かどうか', 'Nhúng câu hỏi có/không vào giữa câu.', '行けるかどうか、まだわかりません。'),
      t('〜につれて', 'V(từ điển)/Noun + につれて', 'Hai sự thay đổi diễn ra song song "theo đà".', '年を取るにつれて、時間が早く感じます。'),
    ],
  },
  {
    id: 'n2',
    label: 'N2 · Trung cao cấp',
    topics: [
      t('Kính ngữ đầy đủ（尊敬語・謙譲語）', 'お + V-ます + になる／いたす', 'Kính ngữ dùng thành thạo trong môi trường công sở.', '資料をお送りいたします。'),
      t('〜において・〜にとって', 'Noun + において (trong bối cảnh); Noun + にとって (đối với)', 'Diễn tả bối cảnh hoặc góc nhìn.', '現代社会において、環境問題は重要だ。'),
      t('〜おかげで・〜せいで', 'V/Noun + おかげで (nhờ có); せいで (tại vì, mang nghĩa tiêu cực)', 'Diễn tả nguyên nhân dẫn đến kết quả tốt/xấu.', '先生のおかげで合格できました。'),
      t('〜にもかかわらず', 'V/Adj/Noun + にもかかわらず', 'Diễn tả sự tương phản, "mặc dù".', '雨にもかかわらず、彼は出かけた。'),
      t('〜あげく・〜末に', 'V-た + あげく／末に', 'Diễn tả kết quả sau một quá trình dài, thường mang sắc thái vất vả.', '長い議論の末に、結論が出た。'),
      t('〜てからでないと', 'V-て + からでないと', 'Diễn tả điều kiện tiên quyết bắt buộc.', '許可を得てからでないと、始められません。'),
      t('〜ざるを得ない', 'V-ない (bỏ ない) + ざるを得ない', 'Diễn tả việc buộc phải làm dù không muốn.', '残業せざるを得ない状況だ。'),
      t('〜うえに', '普通形 + うえに', '"Đã... lại còn..." — chồng thêm một yếu tố cùng chiều.', 'この店は安いうえに、量も多い。'),
      t('〜かねない', 'V-ます (bỏ ます) + かねない', 'Cảnh báo nguy cơ xấu "rất có thể xảy ra".', 'そんな運転をしたら、事故を起こしかねない。'),
      t('〜がち・〜気味', 'V/Noun + がち (hay bị); V/Noun + 気味 (hơi có chiều hướng)', 'Diễn tả khuynh hướng, thường là tiêu cực.', '最近、疲れ気味で、会議に遅れがちだ。'),
      t('〜一方だ・〜つつある', 'V(từ điển) + 一方だ (ngày càng); V-ます + つつある (đang dần)', 'Diễn tả xu hướng thay đổi liên tục.', '物価は上がる一方だ。'),
      t('〜に違いない', '普通形 + に違いない', 'Suy đoán với độ chắc chắn rất cao "nhất định là".', '彼は何か知っているに違いない。'),
      t('〜ものの・〜ながらも', '普通形 + ものの; V-ます/Adj + ながらも', '"Tuy... nhưng..." trong văn phong trang trọng.', '頭ではわかっているものの、なかなか実行できない。'),
      t('〜にわたって・〜を通じて', 'Noun + にわたって (trải suốt); を通じて (thông qua/suốt)', 'Diễn tả phạm vi thời gian/không gian rộng.', '10年にわたって研究を続けてきた。'),
      t('〜をきっかけに・〜に伴って', 'Noun + をきっかけに (nhân dịp); に伴って (kéo theo)', 'Diễn tả sự kiện khởi đầu và thay đổi kéo theo.', '引っ越しをきっかけに、生活を見直した。'),
      t('〜次第', 'V-ます (bỏ ます) + 次第 (ngay khi); Noun + 次第だ (tuỳ thuộc)', 'Hai cách dùng quan trọng: "ngay sau khi" và "tuỳ vào".', '詳細がわかり次第、ご連絡します。'),
    ],
  },
  {
    id: 'n1',
    label: 'N1 · Cao cấp',
    topics: [
      t('〜ずにはいられない', 'V-ない (bỏ ない) + ずにはいられない', 'Diễn tả cảm xúc/hành động không thể kìm nén được.', 'この本を読むと、泣かずにはいられない。'),
      t('〜てやまない', 'V-て + やまない', 'Diễn tả mong muốn/tình cảm mãnh liệt, kéo dài (văn trang trọng).', '彼の成功を願ってやまない。'),
      t('〜が早いか', 'V(từ điển) + が早いか', 'Diễn tả hành động xảy ra ngay lập tức sau hành động khác.', 'ベルが鳴るが早いか、彼は飛び出した。'),
      t('〜ともなると', 'Noun + ともなると', 'Diễn tả "một khi đã ở vị trí/mức độ đó thì...".', '社長ともなると、責任は重い。'),
      t('〜べからず', 'V(từ điển) + べからず', 'Cấm đoán mang văn phong cổ, trang trọng (biển báo, quy định).', '芝生に入るべからず。'),
      t('〜にたえない', 'Noun/V + にたえない', 'Diễn tả điều không chịu nổi/không đáng để làm.', '見るにたえない光景だった。'),
      t('〜きらいがある', 'V(từ điển)/Noun + の + きらいがある', 'Chỉ ra khuynh hướng xấu (nhận xét mang tính phê bình nhẹ).', '彼は物事を悲観的に考えるきらいがある。'),
      t('〜んばかりに', 'V-ない (bỏ ない) + んばかりに', '"Như thể sắp..." — mô tả trạng thái gần chạm ngưỡng.', '泣かんばかりの顔で頼まれた。'),
      t('〜をよそに', 'Noun + をよそに', 'Phớt lờ sự lo lắng/phản đối xung quanh mà vẫn làm.', '親の心配をよそに、彼は留学を決めた。'),
      t('〜ならでは', 'Noun + ならでは(の)', '"Chỉ có ở..." — nét đặc trưng riêng không nơi nào khác có.', '京都ならではの風情を楽しんだ。'),
      t('〜極まりない・〜の極み', 'Adj + 極まりない; Noun + の極み', 'Nhấn mạnh mức độ cực điểm trong văn phong trang trọng.', '彼の態度は失礼極まりない。'),
      t('〜を禁じ得ない', 'Noun + を禁じ得ない', 'Không kìm được cảm xúc (văn viết, phát biểu trang trọng).', 'その決定には疑問を禁じ得ない。'),
      t('〜ゆえに', 'Noun/普通形 + (が)ゆえに', '"Bởi vì" trong văn phong cứng, học thuật.', '経験が浅いがゆえに、失敗することもある。'),
      t('〜なり', 'V(từ điển) + なり', 'Ngay khi vừa làm A thì lập tức B (thường là việc bất ngờ).', '彼は家に帰るなり、部屋に閉じこもった。'),
    ],
  },
];

const JA_BJT_LEVELS = [
  {
    id: 'bjt-basic',
    label: 'Cơ bản · Giao tiếp công sở hàng ngày',
    topics: [
      t('Chào hỏi công việc', 'いつもお世話になっております。', 'Câu chào mở đầu chuẩn mực khi liên hệ công việc, dùng cả điện thoại lẫn email.', 'いつもお世話になっております、ABC商事の田中です。'),
      t('Kính ngữ お+V-ます+になる', 'お + V-ます (bỏ ます) + になる', 'Tôn kính hành động của đối phương (khách hàng, cấp trên).', '資料をお読みになりましたか。'),
      t('Xác nhận lịch sự', '〜でよろしいでしょうか', 'Xác nhận thông tin một cách lịch sự, tránh khẳng định cộc lốc.', '来週の会議は3時でよろしいでしょうか。'),
      t('Xin lỗi trang trọng', '申し訳ございません', 'Mức độ xin lỗi trang trọng nhất, dùng khi làm phiền/gây lỗi với khách hàng.', 'ご迷惑をおかけして申し訳ございません。'),
      t('Tự giới thiệu công việc', '〜と申します。よろしくお願いいたします。', 'Mẫu tự giới thiệu chuẩn khi gặp đối tác/khách hàng lần đầu.', '初めまして、営業部の田中と申します。よろしくお願いいたします。'),
      t('Nghe điện thoại công sở', 'お電話ありがとうございます。〜でございます。', 'Mẫu câu mở đầu cuộc gọi đến công ty.', 'お電話ありがとうございます。ABC商事でございます。'),
      t('〜でございます', 'Noun + でございます', 'Dạng khiêm nhường/lịch sự của です, chuẩn mực khi nói với khách hàng.', 'こちらが新しいカタログでございます。'),
      t('少々お待ちください', '少々お待ちください / お待ちいただけますでしょうか', 'Xin đối phương chờ trong giây lát — thiết yếu khi nghe điện thoại.', '確認いたしますので、少々お待ちください。'),
      t('恐れ入りますが', '恐れ入りますが、〜', 'Câu đệm "làm phiền anh/chị..." trước khi hỏi hoặc nhờ vả.', '恐れ入りますが、お名前を伺ってもよろしいでしょうか。'),
      t('かしこまりました・承知いたしました', 'かしこまりました / 承知いたしました', 'Cách trả lời "tôi đã hiểu/xin vâng" trang trọng thay cho わかりました.', 'かしこまりました。すぐに手配いたします。'),
      t('Chào hỏi nội bộ công ty', 'お疲れ様です / お先に失礼します', 'Các câu chào chuẩn giữa đồng nghiệp trong ngày và khi ra về.', 'お先に失礼します。お疲れ様でした。'),
      t('Nhờ nhắn lại qua điện thoại', '伝言をお願いできますでしょうか', 'Để lại lời nhắn khi người cần gặp vắng mặt.', '恐れ入りますが、伝言をお願いできますでしょうか。'),
    ],
  },
  {
    id: 'bjt-intermediate',
    label: 'Trung cấp · Trao đổi & báo cáo',
    topics: [
      t('Khiêm nhường ngữ khi báo cáo', 'V-ます (bỏ ます) + させていただきます', 'Thông báo hành động của bản thân một cách khiêm tốn, lịch sự.', '本日、資料を送付させていただきます。'),
      t('Hẹn lịch lịch sự', '〜のご都合はいかがでしょうか', 'Hỏi ý kiến đối phương về thời gian một cách lịch sự.', '来週水曜日のご都合はいかがでしょうか。'),
      t('Báo cáo tiến độ/kế hoạch', '〜の予定でございます', 'Thông báo lịch trình hoặc kế hoạch dự kiến.', '納品は来月10日の予定でございます。'),
      t('Từ chối khéo léo', 'あいにく〜', 'Từ chối một cách nhẹ nhàng, không gây mất lòng.', 'あいにく、その日は都合がつきません。'),
      t('Xác nhận lại để tránh hiểu lầm', '〜という理解でよろしいでしょうか', 'Xác nhận lại nội dung đã trao đổi để tránh sai sót.', '来週までに納品するという理解でよろしいでしょうか。'),
      t('Nhờ vả lịch sự', '〜ていただけますでしょうか', 'Mức độ nhờ vả lịch sự cao, thường dùng với khách hàng/cấp trên.', '資料をご確認いただけますでしょうか。'),
      t('お手数をおかけしますが', 'お手数をおかけしますが、〜', 'Câu đệm "phiền anh/chị..." khi nhờ việc tốn công sức của đối phương.', 'お手数をおかけしますが、再度ご確認いただけますでしょうか。'),
      t('Mở đầu theo chủ đề công việc', '〜の件でご連絡いたしました', 'Nêu rõ mục đích liên lạc ngay đầu email/cuộc gọi.', '見積もりの件でご連絡いたしました。'),
      t('Gửi và xin kiểm tra tài liệu', '添付いたします / ご査収ください', 'Mẫu câu chuẩn khi gửi file đính kèm trong email công việc.', '資料を添付いたしますので、ご査収ください。'),
      t('Truyền đạt lời người khác', '〜とのことです', 'Chuyển lời nhắn/thông tin từ người khác một cách trung lập.', '田中は本日休みを取っているとのことです。'),
      t('Câu kết email chuẩn', 'ご確認のほど、よろしくお願いいたします', 'Các mẫu câu chốt email lịch sự, đúng chuẩn thương mại.', 'ご確認のほど、よろしくお願いいたします。'),
      t('拝見・拝読 — khiêm nhường khi xem', '拝見する / 拝読する', 'Động từ khiêm nhường thay cho 見る・読む khi nói về tài liệu của đối phương.', 'ご提案書を拝見いたしました。'),
    ],
  },
  {
    id: 'bjt-advanced',
    label: 'Nâng cao · Đàm phán & xử lý tình huống',
    topics: [
      t('Trình bày tình huống bất khả kháng', '〜せざるを得ない状況でございます', 'Giải thích lý do buộc phải thay đổi kế hoạch một cách trang trọng.', '予算の都合上、計画を変更せざるを得ない状況でございます。'),
      t('Đề xuất kế hoạch trang trọng', '〜の段取りで進めさせていただきたく存じます', 'Đề xuất phương án tiến hành công việc trong văn phong rất trang trọng.', '来月から新体制の段取りで進めさせていただきたく存じます。'),
      t('Xử lý khiếu nại khách hàng', 'ご迷惑をおかけし誠に申し訳ございません', 'Mức xin lỗi cao nhất khi xử lý khiếu nại/sự cố với khách hàng.', 'この度はご迷惑をおかけし誠に申し訳ございません。'),
      t('Đề xuất mềm mỏng trong đàm phán', '〜と存じますが、いかがでしょうか', 'Đưa ra ý kiến một cách khiêm tốn, để ngỏ cho đối phương phản hồi.', 'この条件が妥当かと存じますが、いかがでしょうか。'),
      t('Trình bày số liệu trang trọng', '〜という結果となっております', 'Báo cáo số liệu/kết quả kinh doanh trong văn phong báo cáo chính thức.', '売上は前年比10%増という結果となっております。'),
      t('Kết thúc đàm phán tích cực', '前向きに検討させていただきます', 'Câu chốt thường dùng để khép lại một cuộc đàm phán theo hướng tích cực.', 'ご提案について、前向きに検討させていただきます。'),
      t('Từ chối trang trọng いたしかねます', 'V-ます (bỏ ます) + かねます / いたしかねます', 'Từ chối yêu cầu một cách gián tiếp, chuẩn mực trong thương mại.', '申し訳ございませんが、値引きはいたしかねます。'),
      t('〜次第、ご連絡いたします', 'V-ます (bỏ ます) + 次第、ご連絡いたします', 'Cam kết phản hồi ngay khi có thông tin — giữ nhịp giao tiếp chuyên nghiệp.', '詳細が確定し次第、改めてご連絡いたします。'),
      t('Từ chối đề nghị của đối tác', 'ご意向に沿えず申し訳ございません', 'Xin lỗi vì không đáp ứng được nguyện vọng — dùng khi từ chối chính thức.', '誠に恐縮ですが、ご意向に沿えず申し訳ございません。'),
      t('Xin hỗ trợ trang trọng', 'お力添えいただけますと幸いです', 'Nhờ giúp đỡ với văn phong khiêm nhường cao nhất, thường trong email.', 'ぜひお力添えいただけますと幸いです。'),
      t('弊社・御社・貴社', '弊社 (công ty tôi); 御社 (quý công ty - nói); 貴社 (quý công ty - viết)', 'Cách xưng hô công ty mình và công ty đối tác đúng chuẩn.', '弊社の担当者が御社へ伺います。'),
      t('承る（うけたまわる）', 'ご注文/ご予約を承ります', 'Động từ khiêm nhường "xin tiếp nhận" đơn hàng, yêu cầu, lời nhắn.', 'ご注文を承りました。ありがとうございます。'),
    ],
  },
];

export const ROADMAP = {
  en: {
    label: 'Tiếng Anh',
    flag: '🇬🇧',
    tracks: [
      { key: 'general', label: 'Lộ trình CEFR (A1 → C2)', levels: EN_LEVELS },
    ],
  },
  ja: {
    label: 'Tiếng Nhật',
    flag: '🇯🇵',
    tracks: [
      { key: 'general', label: 'Ngữ pháp tổng quát (N5 → N1)', levels: JA_GENERAL_LEVELS },
      { key: 'bjt', label: 'Tiếng Nhật thương mại (BJT)', levels: JA_BJT_LEVELS },
    ],
  },
};

/** Gán id ổn định cho từng topic: `${lang}-${trackKey}-${levelId}-${index}` — dùng để lưu tiến độ. */
export function topicId(language, trackKey, levelId, index) {
  return `${language}-${trackKey}-${levelId}-${index}`;
}
